name: aashnefleechenblochen
favicon: null
layout_spectrum: 0.11834312882274389
typography_spectrum: 0.8679852918721735
title: 'The site devoted to the infamous, and slightly ephemeral, Joe Aashnefleechenblochen'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.20200099144130945
  lightness: 0.3363353682216257
  saturation: 0.5960781737230718
  rhythmicContrast: 0.6384453657083213
purpose: []
